name: DRF Writable Nested

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            django: 2.2
          - python-version: 3.7
            django: 3.0
          - python-version: 3.7
            django: 3.1
          - python-version: 3.7
            django: 3.2

          - python-version: 3.8
            django: 2.2
          - python-version: 3.8
            django: 3.0
          - python-version: 3.8
            django: 3.1
          - python-version: 3.8
            django: 3.2
          - python-version: 3.8
            django: 4.0

          - python-version: 3.9
            django: 2.2
          - python-version: 3.9
            django: 3.0
          - python-version: 3.9
            django: 3.1
          - python-version: 3.9
            django: 3.2
          - python-version: 3.9
            django: 4.0

          - python-version: "3.10"
            django: 3.2
          - python-version: "3.10"
            django: 4.0
          - python-version: "3.10"
            django: 4.1

          - python-version: "3.11"
            django: 4.0
          - python-version: "3.11"
            django: 4.1

    env:
      PYTHON: ${{ matrix.python-version }}
      DJANGO: ${{ matrix.django }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: PYTHON,DJANGO
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
